### ISSUE TITLE
Create config yaml file(s) for use by tests

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#137]
I want a config file that can be used by the dome tests, and it makes sense to have another such config file for the bisque tests.

The existing POCS/conf_files/pocs.yaml seems to really be the local file for PAN001. Perhaps we need to have some other file as the base yaml file?

Regarding tests, we could use a separate file such as pocs_test.yaml, or even multiple such files so that we can test the effect of having different numbers of cameras, or different state machines. I can't add a dome section to pocs.yaml without it affecting PAN001 and PAN006.

**Comment by wtgee** [comment]
Sorry, this is mostly a documentation issue.

`conf_files.pocs.yaml` is the default config file that should be used for tests and to verify the software runs. It's mostly meant as an example. Any file in the `$POCS/conf_file/` directory can have a `foo_local.yaml` version that will override and add to the `foo.yaml` file. `pocs.yaml` should never be altered, which is why it is part of the repository. A local unit should therefore have a `$POCS/conf_files/pocs_local.yaml` file for any local-specific settings.

**Comment by wtgee** [comment]
Will be closed by #951.
